services:
  fileparser:
    build:
      context: ..
      dockerfile: FileParser/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - LocalFiles__StatusesFolderPath=/data
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    volumes:
      - fileparser-data:/data

  dataprocessor:
    build:
      context: ..
      dockerfile: DataProcessor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - Sqlite__ConnectionString=Data Source=/data/dataprocessor.db
      - ApplyMigrations=true
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    volumes:
      - dataprocessor-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping

volumes:
  fileparser-data:
  dataprocessor-data:
  rabbitmq-data:
