name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build .NET projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build /warnaserror
